### ISSUE TITLE
I can't see all of the projects on the denominational carousel

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#10]
I need to be able to select all of the UCC projects to feature on that page...but they aren't showing up. 

http://www.fundthisministry.org/backoffice/carousel3

**Comment by bikash02** [comment]
Updated the code.
If you get all the projects at a time please change the number of entries dropdown box. 
![screenshot-www fundthisministry org 2016-07-26 19-02-03](https://cloud.githubusercontent.com/assets/16361011/17140545/79bd0c52-5366-11e6-9006-b0d74a33a925.png)

**Comment by bikash02** [comment]
Currently the system have 25 publish and approved projects in UCC
