### ISSUE TITLE
I can't load a project using WePay because the SSL certificate is not active

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#11]
Getting this error:

![screen shot 2016-07-11 at 5 41 14 pm](https://cloud.githubusercontent.com/assets/15096099/16774808/af2750e6-482b-11e6-9454-2a36b1efc5b4.png)

**Comment by bikash02** [comment]
@debdiproy was resolved the issue.
If you are still getting the same issue please let us know.

**Comment by debdiproy** [comment]
Resolved
