### ISSUE TITLE
Responsive Issues with main page

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#12]
![img_0029](https://cloud.githubusercontent.com/assets/15096099/17229522/e4eb69ee-54e5-11e6-8388-6ce4cdb701cf.jpg)
![img_0030](https://cloud.githubusercontent.com/assets/15096099/17229523/e4ec20e6-54e5-11e6-9809-4432a6f7a053.jpg)

**Comment by i-puspita** [comment]
updated
