### ISSUE TITLE
Error when making donation

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#14]
![screen shot 2016-08-31 at 12 14 25 pm](https://cloud.githubusercontent.com/assets/15096099/18136965/962b3cfe-6f74-11e6-84ae-334df140bb8a.png)

**Comment by bikash02** [comment]
You are getting the error because you’re using a live access token while in test mode.

**Comment by camerontrimble** [comment]
But we should be in live mode...not test
