### ISSUE TITLE
Can't click to get off this page

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#15]
I created a WePay account and was redirected back to this page in our system. But now I can't click anywhere to get to a new section of the site. 

![screen shot 2016-09-02 at 3 41 15 pm](https://cloud.githubusercontent.com/assets/15096099/18216300/d602fd02-7123-11e6-8ff6-db550463ce93.png)

**Comment by debdiproy** [comment]
Duplicate
