### ISSUE TITLE
Sidebar not working with images

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#17]
![screen shot 2016-09-02 at 4 02 51 pm](https://cloud.githubusercontent.com/assets/15096099/18216741/c3d2b2be-7126-11e6-9ac5-3ebf15bb330e.png)

**Comment by bikash02** [comment]
Please follow the below steps in visual mode in editor.
1.Place the cursor where you want to put the image.
2.Click on "Picture" icon and upload it from your local storage .
3.Click on "Update".

Ping me if you still getting the same error..
