### ISSUE TITLE
Can we make the project owner a dropdown box of all users in the SUPER ADMIN profile?

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#21]
I have a situation where I need to change the owner of a project. Can we give the Super Admin permission to select a new user? The other permission levels should not have that access. 
![screen shot 2016-09-03 at 11 40 57 am](https://cloud.githubusercontent.com/assets/15096099/18225833/7fd11196-71cb-11e6-8fb2-5e7b30890ea4.png)

**Comment by bikash02** [comment]
updated
