### ISSUE TITLE
Format issue on the donate page

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#23]
![screen shot 2016-09-03 at 11 52 55 am](https://cloud.githubusercontent.com/assets/15096099/18225909/03f350b4-71cd-11e6-83bf-09f6e1e4132f.png)

**Comment by bikash02** [comment]
It's a browser compatible issue.So please tell me in which browser you checked and the issue was found in desktop or mobile view?

**Comment by bikash02** [comment]
According to your feedback we'll update the code.

**Comment by camerontrimble** [comment]
I'm using Chrome

**Comment by bikash02** [comment]
@i-puspita please check the browser compatibility issues.

**Comment by i-puspita** [comment]
Please check & inform if the issue is resolved or not as, there is no such error in our browser.
