### ISSUE TITLE
WePay issue

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#30]
I connected a WePay account to a new user in FTM. I was redirected to this page which makes no sense.
![screen shot 2016-09-21 at 5 37 55 pm](https://cloud.githubusercontent.com/assets/15096099/18730079/7a522c40-8022-11e6-8eb0-22296e96a8a1.png)

Then I got this error:

![screen shot 2016-09-21 at 5 38 18 pm](https://cloud.githubusercontent.com/assets/15096099/18730094/87eb9198-8022-11e6-86ba-72ea9e325394.png)

**Comment by bikash02** [comment]
The form was not validated so you were getting the error .We have updated the page.
Please try once again and keep me update.
