### ISSUE TITLE
Delete this footer

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#31]
Let's just remove all of this complete. Please find another place to display the SSL certificate icon. 
![screen shot 2016-10-04 at 2 27 00 pm](https://cloud.githubusercontent.com/assets/15096099/19087091/c4244094-8a3e-11e6-996f-af6712a53122.png)

**Comment by Designer-cleonix** [comment]
@bikash02

**Comment by bikash02** [comment]
updated
