### ISSUE TITLE
Emails from this site should be from Fund This Ministry, not Convergence Support, to avoid confusion 

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#33]

**Comment by debajyotiGuha** [comment]
All from email ids are changed to 'support@fundthisministry.org' And label changed to 'Fund This Ministry Support'.

**Comment by bikash02** [comment]
@camerontrimble We have updated the issue please check.

**Comment by camerontrimble** [comment]
Where do these emails go? I sent a test email but never received it. Can you have them forwarded to cameron@convergenceus.org?

**Comment by bikash02** [comment]
@debajyotiGuha Please update the email id from "cameron@progressiverenewal.org" to "cameron@convergenceus.org"

**Comment by debajyotiGuha** [comment]
Emails changed.

**Comment by bikash02** [comment]
@camerontrimble updated your email id.
