### ISSUE TITLE
Error with therobots.txt file.Unable to load the requested file: meta.php

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#35]

**Comment by bikash02** [comment]
I started off by going to browsershots.org to try and see how the site renders across different browsers. Unfortunately I was unable to run the tool—Browsershots told me that there was an error with the robots.txt file. I tried to pull up the robots.txt file myself and got the error

**Comment by bikash02** [comment]
We have uploaded the robots.txt file.

**Comment by bikash02** [comment]
We tested the site in browsershots and getting the same error but we have tested browserstack and its working.https://www.browserstack.com/

**Comment by camerontrimble** [comment]
Not sure if this is completed or not...if so, please close.
