### ISSUE TITLE
Chat  not response

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#37]
Chat was on and off while I was testing the site. I might have had an open browser that still said chat was available after it had been switched off, but when I attempted to start a conversation I got through to the chat screen and waited there for a while without a response.

**Comment by debajyotiGuha** [comment]
It's  a 3rd party plugin and we can't alter the code.Its happen maybe something goes wrong into their server or maybe in browser issue or crash.Please try again and keep me posted  with the response.

**Comment by bikash02** [comment]
I have tested and found the cause.The chat API is activated for the current page.If you open two separate pages in a same browser,It will work for the current page and another one was inactive and in that case you have to reload the second page for getting or initiating the chat.

**Comment by amyolrick** [comment]
Great, thank you!
