### ISSUE TITLE
Error when making a donation

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#38]
I received this error when I attempted to make a donation to We Stand With Love.
**"This app does not have permission to make tokenization API calls. You can request approval from your app dashboard on WePay."**

**Comment by bikash02** [comment]
I did a few more things on the site before I attempted another donation, this time to the Atlanta dinnerchurch. I noticed my email address was pulled into the cc number field. I replaced my email address with my card number and attempted the donation several times, but every time it processed it returned the below error, and with my email address again pulled into the cc field.

**Comment by bikash02** [comment]
@debajyotiGuha Please make the form autocomplete off.

**Comment by debajyotiGuha** [comment]
Form autocomplete turn off.

**Comment by bikash02** [comment]
The error occurred because your WePay account hasn’t been authorized for token creation.

**Comment by bikash02** [comment]
@camerontrimble  We have updated the wepay code last week and please make a donate using wepay and if there was an error please push on the githhub..
