### ISSUE TITLE
Beta Testing : Setting up an account

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#39]
1.Something I did using the system, either initiating a chat or attempting to make a donation, created a user account for me. This triggered an email that included a password. Do we want these accounts to be automatically generated like this? I think not.

2.One thing I noticed is that the actual account creation requests an EIN number. I assume that a ssl would work there as well, right? I am thinking that requesting that info in this beginning stage might be off-putting to people.Companies like Amazon and CaféPress request this info before they make a payout. Could this be a possibility? People who have collected money would then be motivated to pass on this info, but the merely curious could still create accounts and look around.

**Comment by bikash02** [comment]
@camerontrimble @debdiproy  Need to discuss with you.

**Comment by amyolrick** [comment]
Please let me know when you are available to discuss--my skype id is amy.olrick and my whatsapp's is +17572327354

**Comment by camerontrimble** [comment]
This site is designed to manage 501c3 donations so we ask for the EIN number. Otherwise we can't vouch for the tax deductible status of gifts given through the site. But we should talk about if we want to keep that requirement in place @amyolrick

**Comment by bikash02** [comment]
So please assist me what to do regarding the issue.Should I leave for the moment?

**Comment by camerontrimble** [comment]
Let's change that field to "EIN or Social Security Number"

**Comment by debajyotiGuha** [comment]
Updated.
