### ISSUE TITLE
Beta testing: Setting up a project

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#40]
1. We need to add a $ in front of the amount field so that people don’t add that in themselves
2. I think that a few more lines of explanation would be helpful when people are prompted to create a WePay account. And I need to make sure I understand theWePay process myself as we move forward.

3.In Chrome I got stuck on the “Add a new project” page—there was no way to scrolldown. I was able to proceed with Safari.

4.Creating the project looks great! I wonder is we should have less customization options for the text, but that’s not necessary, it would just keep things uniform across all projects.
5. I created a project as a draft, and noticed that I got three messages, all from Convergence Support, telling me that my project had not been approved. I never finalized it so I don’t think that I should have received these messages. We should go through the flow and figure out when messages are sent out and customize the messages.

**Comment by bikash02** [comment]
Point 1 & 2 updated

**Comment by debajyotiGuha** [comment]
Point 5. sending mail updated. When an user post a new project with status as publish they will get  email and the admin will also get  a copy and when admin will approve the project the user will also get an email confirmation.

**Comment by bikash02** [comment]
@debajyotiGuha Please hide the color for the text and make it uniform for all the projects.

**Comment by debajyotiGuha** [comment]
Colors hidden from project edit page and make uniform for all the projects.

**Comment by bikash02** [comment]
@i-puspita @Designer-cleonix Please update point no 3 having browser compatibility issue.

**Comment by i-puspita** [comment]
point no 3 is updated

**Comment by bikash02** [comment]
@camerontrimble We have updated all the above points.Please check from your end.

**Comment by camerontrimble** [comment]
@amyolrick will you take a look and see what you think?

**Comment by camerontrimble** [comment]
On #5, Let's send an email that says:

Thank you for posting a project to FundThisMinistry.org. We will review your project immediately. Within the next 24 hours, we will either make it live on the main site or reply back with further suggestions for ways to strengthen your project. You are welcome to make changes to your project at any time. 

We appreciate your partnership. Email us at support@fundthisministry.org if you have any questions. We will be in touch soon!

The FundThisMinistry.org Team

**Comment by amyolrick** [comment]
Looking into #3 now. I am still not seeing the scrollbar and am trying to looking into the code to see if I can figure out why. I can tab through the fields but not scroll. I had a similar issue with a site I built last year and it ended up being a javascript issue.

**Comment by amyolrick** [comment]
Ok, I am now seeing the scrollbar! Great work--you fixed it!

**Comment by bikash02** [comment]
Updated the email text.

**Comment by camerontrimble** [comment]
Can you work on the formatting? This is how it looks when it comes through in my inbox. 

![screen shot 2016-10-25 at 8 27 56 am](https://cloud.githubusercontent.com/assets/15096099/19685987/2adf5694-9a8d-11e6-86ca-385b3879b7bd.png)

**Comment by bikash02** [comment]
Yes.The designer will update you asap.

**Comment by bikash02** [comment]
@camerontrimble Please check we have updated.
If you need an email template like CMP then we will configure and update the code within next one day.Leave your comment please.

**Comment by camerontrimble** [comment]
Yes, let's do a formatted email like the music project site. It will look better. Thanks.

**Comment by bikash02** [comment]
@debajyotiGuha Please update the email templates for the pages including backend & frontend.

**Comment by debajyotiGuha** [comment]
Email templates updated for the pages including backend & frontend.

**Comment by bikash02** [comment]
@camerontrimble Please check we have updated the email templates.

**Comment by camerontrimble** [comment]
Formatting Issues

![screen shot 2016-10-26 at 9 19 29 am](https://cloud.githubusercontent.com/assets/15096099/19727426/66b90d74-9b5d-11e6-8294-4d96049960e7.png)

**Comment by bikash02** [comment]
updated
