### ISSUE TITLE
Check site speed

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#41]
The site is running really slowly for me...and my connection speed is fine. Specifically, it is taking a long time to pull up individual projects.

**Comment by bikash02** [comment]
@debajyotiGuha Please create an account and test the website and make it more optimize.
https://gtmetrix.com/

**Comment by bikash02** [comment]
@camerontrimble We have optimized the site including js & css and some images as well.
Before Optimize Load Time: 6.00 s
After Optimize Load Time: 3.40 s
**Note: Set the leverage browser caching for loading the website fast.**

Please check the website now and leave your comment.

**Comment by bikash02** [comment]
You'll get more info from the attached file.
[fundthismynistry assets update list.ods.zip](https://github.com/ConvergenceUS/fundthisministry/files/558181/fundthismynistry.assets.update.list.ods.zip)
