### ISSUE TITLE
WePay and Paypal issues

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#42]
We just had a person load a new project into the system. They set up a WePay account. They then made a donation and it went into our Paypal account. Something is wrong. 

![screen shot 2016-10-26 at 5 10 55 pm](https://cloud.githubusercontent.com/assets/15096099/19745387/68140bdc-9b9f-11e6-85bb-22e877625d4c.png)

**Comment by bikash02** [comment]
@debdiproy I need to discuss with you regarding the issue.I want a test drive to make sure and debugging the error instantly.Please ping me when you get free.
https://www.fundthisministry.org/project/wepayform/84|70|

**Comment by Designer-cleonix** [comment]
@debdiproy please do the needful.

**Comment by camerontrimble** [comment]
We lost this client today because it took too long to get this issue resolved. They had their WePay account set up correctly. The problem is in our system. At present, no new donors/users in the system can make donations. This is ridiculous. We had three days to fix this issue and we didn't get it solved. Needless to say, I am very disappointed and concerned that we get this issue resolved immediately.

**Comment by debdiproy** [comment]
I got on with the client and has resolved their issue and to be honest Cameron they did not set up their Wepay account correctly thus they could not pay but I have helped them to set it up correctly and it is working fine now.
