### ISSUE TITLE
Format this email

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#43]
![screen shot 2016-10-26 at 5 10 55 pm](https://cloud.githubusercontent.com/assets/15096099/19745417/859f2d94-9b9f-11e6-9e3c-0bcf03d2a57b.png)

**Comment by debajyotiGuha** [comment]
Email template formatted for mail after donation.

**Comment by camerontrimble** [comment]
We still have formatting issues on this email as of this morning.

**Comment by Designer-cleonix** [comment]
@debajyotiGuha Solve this ASAP.

**Comment by debajyotiGuha** [comment]
Email template formatted. Please check once.
