### ISSUE TITLE
Format this email after a donation goes through

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#46]
![screen shot 2016-10-26 at 8 25 08 pm](https://cloud.githubusercontent.com/assets/15096099/19750013/bef09ada-9bbb-11e6-8a25-5de9fe8d97fc.png)

**Comment by bikash02** [comment]
@debajyotiGuha I didn't get any update from you.Please let me know the status.

**Comment by debajyotiGuha** [comment]
Email template formatted for mail after donation.

**Comment by camerontrimble** [comment]
Make sure that the date field is formatted to US format. 

![screen shot 2016-10-31 at 10 49 43 am](https://cloud.githubusercontent.com/assets/15096099/19861054/7b3e89ce-9f61-11e6-90e0-ba520ab0340f.png)

**Comment by Designer-cleonix** [comment]
@debajyotiGuha Update this ASAP.

**Comment by debajyotiGuha** [comment]
Date format changed.
