### ISSUE TITLE
Please check the contact us form

### ISSUE THREAD

**Issue by bikash02** [ConvergenceUS/fundthisministry#48]
Add the email template and reconfigure it.
https://www.fundthisministry.org/contact-us

**Comment by bikash02** [comment]
Please remove support@convergenceus.org from the site..

**Comment by debajyotiGuha** [comment]
Removed.

**Comment by debajyotiGuha** [comment]
Email template added for contact us form.

**Comment by bikash02** [comment]
Thanks
