### ISSUE TITLE
We need to associate a user with a project on the project page

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#5]

**Comment by debdiproy** [comment]
Is this for super admin or denominational admin

**Comment by camerontrimble** [comment]
We need to associate a project with a owner on this table: 
![screen shot 2016-08-31 at 11 55 15 am](https://cloud.githubusercontent.com/assets/15096099/18136002/d0533c2c-6f71-11e6-9c01-711ecab033a8.png)

Right now, I can't tell who has created what...

**Comment by bikash02** [comment]
updated the project owner under "General" tab.

**Comment by camerontrimble** [comment]
Can we make that linkable to the user profile so that we can easily find their email address?

**Comment by bikash02** [comment]
updated
