### ISSUE TITLE
Sample blog posts public

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#50]
On the sidebar on the blog page, there's about three "sample blog" posts that have no text. One of them is supposed to be a song but it does not have the link or song available. 
<img width="779" alt="screen shot 2016-11-04 at 6 21 16 pm" src="https://cloud.githubusercontent.com/assets/23104131/20024194/89a31964-a2bb-11e6-9c8e-a94cae37d788.png">

**Comment by bikash02** [comment]
This blog was posted by "Amy Sens" . Please request the owner or admin to put some content from the backoffice and update the post.You are getting the message due to wrong link.

**Comment by bikash02** [comment]
Here is the link: https://bandcamp.com/EmbeddedPlayer/track=2141139164/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=small/transparent=true/

**Comment by rikalively** [comment]
I don't have access to contact the owner of the blog post. Also, the bandcamp link gives me the same message.

**Comment by bikash02** [comment]
@camerontrimble Please update the blog content or make it archive from the backoffice.

**Comment by camerontrimble** [comment]
Done!
