### ISSUE TITLE
Cannot click archives link

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#51]
Many of the recent blogs are on the sidebar but none of them are clickable.
<img width="389" alt="screen shot 2016-11-04 at 6 22 11 pm" src="https://cloud.githubusercontent.com/assets/23104131/20024228/acfed902-a2bb-11e6-9a80-011ebafd0b05.png">

**Comment by debajyotiGuha** [comment]
Working on it. Updated by today.

**Comment by debajyotiGuha** [comment]
Filter by category and timeline updated.

**Comment by rikalively** [comment]
The links are now clickable! But the links for July 2015, September 2015, and January 2016 take you to a blank page. 
<img width="1440" alt="screen shot 2016-11-07 at 9 08 01 am" src="https://cloud.githubusercontent.com/assets/23104131/20060587/e7fa2a4c-a4c9-11e6-83f6-a7af25982d89.png">

**Comment by debajyotiGuha** [comment]
Cause there are no posts in that time span, hence it shows a blank page. Give me the proper instruction, which data will be shown in archive filter and I will change it like that.

**Comment by rikalively** [comment]
Okay, I see that you removed the inactive links. I think the main thing is making sure we have working links on the page. 
I don't have the blog posts that would have been archived in those months. It's looking better now.
Thank you
