### ISSUE TITLE
Tried to create a new project

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#53]
This is the page I got when I tried to submit a new project.
<img width="1349" alt="screen shot 2016-11-07 at 12 13 59 pm" src="https://cloud.githubusercontent.com/assets/23104131/20067637/f244f7d8-a4e3-11e6-994f-44f663aa18ef.png">

**Comment by Designer-cleonix** [comment]
This error seems to be a same name posting. Can you verify once.

**Comment by rikalively** [comment]
Yes that was the issue!
However, I lost all of my work in trying to create a project because I had the same name as someone else. Is there a different way for the site to handle this issue. Instead it could just give me an error message saying I need to choose a different name since that name already exists? 
I think people will get very frustrated if they lose all of their work and getting that big error screen.
Thank you!

**Comment by bikash02** [comment]
@debajyotiGuha Please validate the add project form and make it user friendly more.

**Comment by debajyotiGuha** [comment]
Solved.

**Comment by bikash02** [comment]
@rikalively please check once again.We have validated the duplicate project name.

**Comment by rikalively** [comment]
I put in a duplicate name and got the same "database error" message as before. I was able to finish the form and hit submit. That's when the error message occurs.

**Comment by debajyotiGuha** [comment]
Issue solved. No duplicate entry possible.

**Comment by rikalively** [comment]
I can still get to this page after completing the form.
If the name is the last thing I put in, it will let me continue. 

<img width="1347" alt="screen shot 2016-11-09 at 9 33 40 am" src="https://cloud.githubusercontent.com/assets/23104131/20141717/9e266826-a65f-11e6-882b-588666c5b07c.png">

**Comment by debajyotiGuha** [comment]
That possibility stopped also. Only with valid name a project can be submit.

**Comment by rikalively** [comment]
Thank you! Working now
