### ISSUE TITLE
Project not published

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#54]
My dashboard says my project is published but I cannot find it on the actual project list. 
<img width="1159" alt="screen shot 2016-11-07 at 1 16 28 pm" src="https://cloud.githubusercontent.com/assets/23104131/20069981/c5aa61d2-a4ec-11e6-85f9-8eb3627776d9.png">

**Comment by camerontrimble** [comment]
I have to approve it before it appears live on the site. Check your email and make sure that you get an email saying as much. I will approve it now so that you can keep testing.

**Comment by rikalively** [comment]
Silly me - I closed my email tab. That makes sense! Thank you
