### ISSUE TITLE
Cannot upload a banner on project page

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#55]
I've been trying to upload a banner for my project but it won't update/save

<img width="1440" alt="screen shot 2016-11-07 at 1 34 12 pm" src="https://cloud.githubusercontent.com/assets/23104131/20070558/e14ee4ce-a4ee-11e6-9245-06830fa58f27.png">

**Comment by bikash02** [comment]
Please select "Display" option under branding tab.

**Comment by bikash02** [comment]
either you select a featured image or video

**Comment by rikalively** [comment]
Okay, I didn't realize the image would take the place of the video. Maybe somewhere on the form we can say featured image or featured video. I know the display option has you choose between the two but it still wasn't clear to me that I was picking between the two. 
Thank you!

**Comment by bikash02** [comment]
Kindly check the page once again.If you select display type as image then you'll able to enter featured image and if you select display type as video then you'll able to put the video link.

If you want more please let us know we'll update accordingly.

**Comment by rikalively** [comment]
That's perfect! Thank you @bikash02
