### ISSUE TITLE
Misleading graphs on user dashboard

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#56]
These graphs on my user dashboard show some revenue - however, I don't have any active projects receiving donations. Why is it showing that I have $6985 for total revenue?

<img width="897" alt="screen shot 2016-11-07 at 11 57 06 am" src="https://cloud.githubusercontent.com/assets/23104131/20103019/462c16da-a596-11e6-85a8-1c32b4879ce2.png">
<img width="958" alt="screen shot 2016-11-08 at 9 32 05 am" src="https://cloud.githubusercontent.com/assets/23104131/20103018/4620410c-a596-11e6-9874-e740eebbd9fd.png">

**Comment by bikash02** [comment]
@debajyotiGuha Please create a separate dashboard for users.

**Comment by bikash02** [comment]
You have to create basically three different dashboard  for User,Administrator & Denomination Admin
Or build the logic and update the sql queries to the current dashboard page.

**Comment by debajyotiGuha** [comment]
Updated. Changed queries.

**Comment by rikalively** [comment]
Thank you!
