### ISSUE TITLE
Let's add a "Added By" to this email with the user name or email address

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#57]
![screen shot 2016-11-08 at 9 38 06 am](https://cloud.githubusercontent.com/assets/15096099/20103243/326129be-a597-11e6-99a2-071eb077d641.png)

**Comment by debajyotiGuha** [comment]
It will be updated by tomorrow.

**Comment by debajyotiGuha** [comment]
Updated.

**Comment by bikash02** [comment]
@camerontrimble Please check.Added the user fullname to this email.
