### ISSUE TITLE
User settings do not save

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#60]
Anything of the setting I change - like my name or picture - do not save.

**Comment by bikash02** [comment]
@debajyotiGuha Please display data from table not from session.

**Comment by debajyotiGuha** [comment]
Problem solved. Please check once.

**Comment by rikalively** [comment]
Some of them are saving but if I remove my picture it does not save. My picture is still showing after I delete it.

**Comment by Designer-cleonix** [comment]
@debajyotiGuha take care of this.

**Comment by debajyotiGuha** [comment]
In my browser it's working fine. Please tell me the scenario where did this happens. Or write the problem in details.

**Comment by bikash02** [comment]
@rikalively I have updated the code.Please try to update your profile and let me know if anything goes wrong.

**Comment by rikalively** [comment]
Working now. Thank you @bikash02
