### ISSUE TITLE
Send an automatic email when a project is approved

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#63]
When the project is made "Active" for the first time, send the project owner an email with the following text:

Your project on Fundthisministry.org is now live! It's time to start raising money by letting your congregation, friends and family know. If you run into any problems, email us at support@fundthisministry.org. We are here to help.

The Fund This Ministry Team

**Comment by debajyotiGuha** [comment]
It will be updated before end of today.

**Comment by debajyotiGuha** [comment]
Updated the email text. Please check once.
