### ISSUE TITLE
New Account Screen Glitchy

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#65]
<img width="821" alt="screen shot 2016-12-22 at 10 08 01 pm" src="https://cloud.githubusercontent.com/assets/23104131/21446360/21061354-c893-11e6-9ff4-9bcb2d035c5b.png">

On this new account screen, if you put in an incorrect email or accidentally click the next box before you finish, it freezes and won't let you finish typing the email. The only way out of the screen is to close the tab.

**Comment by debajyotiGuha** [comment]
Problem resolved. Please check once.

**Comment by rikalively** [comment]
Great! Thank you
