### ISSUE TITLE
Account Login Should Take You to Home Page

### ISSUE THREAD

**Issue by rikalively** [ConvergenceUS/fundthisministry#66]
When a user logs into the website, instead of taking you to the admin page, it should just log you in and you should still see the home page of the website. 
I think this will confuse most users who are just trying to donate to projects. This admin page is overwhelming for someone who is not interested in starting a project and it looks like they somehow got into the backend of the site.
Can we find a way for this page to only be seen if someone decides to start a project. For example, a user wouldn't have access to this page until they fill out the form to start a project. 

Thank you!

**Comment by debajyotiGuha** [comment]
User send to home page after login. Please check once.

**Comment by rikalively** [comment]
Thanks!
