### ISSUE TITLE
People are still choosing my paypal account as their payment method. WePay isn't showing for them. 

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#8]
![screenshot 2016-04-01 08 22 36](https://cloud.githubusercontent.com/assets/15096099/14206694/ef295804-f7e2-11e5-8c08-519e27951b62.png)

**Comment by debdiproy** [comment]
We pay has been added and the convergence payment method has been removed. User can set up their own account now.
