### ISSUE TITLE
Add DATE to the column list

### ISSUE THREAD

**Issue by camerontrimble** [ConvergenceUS/fundthisministry#9]
Date entered into the system: http://www.fundthisministry.org/backoffice/project

**Comment by bikash02** [comment]
updated

**Comment by camerontrimble** [comment]
Can you add "Date Created" so that I can easily see the new projects in the system?

**Comment by bikash02** [comment]
There wasn't any project "create date" in the system but I can do one thing I will change the query and the new projects will display first.

**Comment by camerontrimble** [comment]
Perfect, thanks

**Comment by bikash02** [comment]
Updated.
https://www.fundthisministry.org/backoffice/project
